name: build

on: [push]

env:
  BUILDROOT_VERSION: 2022.05

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache toolchain
        id: toolchain-cache
        uses: actions/cache@v2
        with:
          path: buildroot-${{ env.BUILDROOT_VERSION }}
          key: ${{ env.BUILDROOT_VERSION }}-${{ hashFiles('tcdefconfig') }}
      - name: get Buildroot and build toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          curl https://buildroot.org/downloads/buildroot-$BUILDROOT_VERSION.tar.xz | tar -xJ
          cd buildroot-$BUILDROOT_VERSION
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make toolchain
      # TODO: cache on defconfig changes ?
      - name: build everything
        run: |
          cd buildroot-$BUILDROOT_VERSION
          # contains fix for CVE-2022-33903
          sed -i 's/TOR_VERSION = 0.4.7.7/TOR_VERSION = 0.4.7.8/' package/tor/tor.mk
          sed -i 's/sha256  3e131158b52b9435d7e43d1c47ef288b96d005342cc44b8c950bb403851a5b44  tor-0.4.7.7.tar.gz/sha256  9e9a5c67ad2acdd5f0f8be14ed591fed076b1708abf8344066990a0fa66fe195  tor-0.4.7.8.tar.gz/' package/tor/tor.hash
          cp ../busybox.config .
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make
      - name: save results
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: buildroot-${{ env.BUILDROOT_VERSION }}/output/images
