name: build

on: [push]

env:
  BUILDROOT_VERSION: 2022.11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: set arch
        run: sed -i s/@arch@/${{ matrix.arch }}/ tcdefconfig
      - name: cache toolchain
        id: toolchain-cache
        uses: actions/cache@v3
        with:
          path: buildroot-${{ env.BUILDROOT_VERSION }}
          key: ${{ env.BUILDROOT_VERSION }}-${{ hashFiles('tcdefconfig') }}
      - name: get Buildroot and build toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          curl https://buildroot.org/downloads/buildroot-$BUILDROOT_VERSION.tar.xz | tar -xJ
          cd buildroot-$BUILDROOT_VERSION
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make toolchain
      # TODO: cache on defconfig changes ?
      - name: build everything
        run: |
          cd buildroot-$BUILDROOT_VERSION
          sed -i 's/TOR_VERSION = 0.4.7.8/TOR_VERSION = 0.4.7.10/' package/tor/tor.mk
          sed -i 's/sha256  9e9a5c67ad2acdd5f0f8be14ed591fed076b1708abf8344066990a0fa66fe195  tor-0.4.7.8.tar.gz/sha256 647e56dfa59ea36dab052027fcfc7663905c826c03509363c456900ecd435a5b  tor-0.4.7.10.tar.gz/' package/tor/tor.hash
          cp ../busybox.config .
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make
      - name: save results
        uses: actions/upload-artifact@v3
        with:
          name: images-${{ matrix.arch }}
          path: buildroot-${{ env.BUILDROOT_VERSION }}/output/images
