name: build

on: [push]

env:
  BUILDROOT_VERSION: 2022.02

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache toolchain
        id: toolchain-cache
        uses: actions/cache@v2
        with:
          path: buildroot-${{ env.BUILDROOT_VERSION }}
          key: ${{ env.BUILDROOT_VERSION }}-${{ hashFiles('tcdefconfig') }}
      - name: get Buildroot and build toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          curl https://buildroot.org/downloads/buildroot-$BUILDROOT_VERSION.tar.xz | tar -xJ
          cd buildroot-$BUILDROOT_VERSION
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make toolchain
      - name: copy Knot and LMDB packages
        run: |
          cp -r knot liblmdb buildroot-$BUILDROOT_VERSION/package
          sed -i -e '2247a	source "package/knot/Config.in"' \
                 -e '1443a	source "package/liblmdb/Config.in"' \
                 buildroot-$BUILDROOT_VERSION/package/Config.in
      - name: fast-fail invisible-mirror.net per https://github.com/actions/virtual-environments/issues/2577#issuecomment-845126269
        run: echo "1.1.1.1 invisible-mirror.net" | sudo tee -a /etc/hosts
      # TODO: cache on defconfig changes ?
      - name: build everything
        run: |
          cd buildroot-$BUILDROOT_VERSION
          cp ../busybox.config .
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make
      - name: save results
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: buildroot-${{ env.BUILDROOT_VERSION }}/output/images
