name: build

on: [push]

env:
  BUILDROOT_VERSION: 2023.08

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: set arch
        run: sed -i s/@arch@/${{ matrix.arch }}/ tcdefconfig
      - name: cache toolchain
        id: toolchain-cache
        uses: actions/cache@v3
        with:
          path: buildroot-${{ env.BUILDROOT_VERSION }}
          key: ${{ env.BUILDROOT_VERSION }}-${{ hashFiles('tcdefconfig') }}
      - name: get Buildroot and build toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          curl https://buildroot.org/downloads/buildroot-$BUILDROOT_VERSION.tar.xz | tar -xJ
          cd buildroot-$BUILDROOT_VERSION
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make toolchain
      - name: use newer postgres hoping nothing breaks (https://git.buildroot.net/buildroot/commit/?id=c9bd02911565819789120370178e82da5dfbacc0)
        run: |
          cd buildroot-$BUILDROOT_VERSION/package/postgresql
          sed -i 's/POSTGRESQL_VERSION = 13.5/POSTGRESQL_VERSION = 14.1/' postgresql.mk
          sed -i 's/sha256  9b81067a55edbaabc418aacef457dd8477642827499560b00615a6ea6c13f6b3  postgresql-13.5.tar.bz2/sha256  4d3c101ea7ae38982f06bdc73758b53727fb6402ecd9382006fa5ecc7c2ca41f  postgresql-14.1.tar.bz2/' postgresql.hash
      # TODO: cache on defconfig changes ?
      - name: build everything
        run: |
          cd buildroot-$BUILDROOT_VERSION
          cp ../busybox.config .
          cat ../tcdefconfig ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make
      - name: save results
        uses: actions/upload-artifact@v3
        with:
          name: images-${{ matrix.arch }}
          path: buildroot-${{ env.BUILDROOT_VERSION }}/output/images
