name: build

on: [push]

env:
  BUILDROOT_VERSION: 2021.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache toolchain
        id: toolchain-cache
        uses: actions/cache@v2
        with:
          path: buildroot-${{ env.BUILDROOT_VERSION }}
          key: ${{ env.BUILDROOT_VERSION }}-${{ hashFiles('basedefconfig') }}
      - name: get Buildroot and build toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          curl https://buildroot.org/downloads/buildroot-$BUILDROOT_VERSION.tar.xz | tar -xJ
          cd buildroot-$BUILDROOT_VERSION
          cat ../basedefconfig ../defconfig >defconfig
          cp ../busybox.config .
          make BR2_DEFCONFIG=defconfig defconfig
          make toolchain
      # TODO: cache on defconfig changes ?
      - name: build everything
        run: |
          cd buildroot-$BUILDROOT_VERSION
          cat ../basedefconfig ../defconfig >defconfig
          make BR2_DEFCONFIG=defconfig defconfig
          make
      - name: save results
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: buildroot-${{ env.BUILDROOT_VERSION }}/output/images
